pool:
  name: local
  demands:
  - msbuild
  - visualstudio
  - DotNetFramework

#Your build pipeline references the ‘BuildPlatform’ variable, which you’ve selected to be settable at queue time. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab, and then select the option to make it settable at queue time. See https://go.microsoft.com/fwlink/?linkid=865971
#Your build pipeline references the ‘BuildConfiguration’ variable, which you’ve selected to be settable at queue time. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab, and then select the option to make it settable at queue time. See https://go.microsoft.com/fwlink/?linkid=865971

variables:
- name: 'BuildPlatform'
  value: 'any cpu'
- name: 'BuildConfiguration'
  value: 'release'

steps:
- task: NuGetInstaller@0
  displayName: 'NuGet restore'
  inputs:
    solution: FabrikamFiber.CallCenter.sln

- task: VSBuild@1
  displayName: 'Build solution'
  inputs:
    vsVersion: 15.0
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactstagingdirectory)\\"'
    platform: '$(BuildPlatform)'
    configuration: '$(BuildConfiguration)'

- task: CopyFiles@2
  displayName: 'Copy Files to: $(Build.BinariesDirectory)'
  inputs:
    SourceFolder: '$(build.sourcesDirectory)\FabrikamFiber.Web/obj/Release/Package/PackageTmp'
    TargetFolder: '$(Build.BinariesDirectory)'
    CleanTargetFolder: true

- task: octopusdeploy.octopus-deploy-build-release-tasks.octopus-pack.OctopusPack@2
  displayName: 'Package FabrikamFiber'
  inputs:
    PackageId: FabrikamFiber
    PackageFormat: Zip
    PackageVersion: '1.0.$(Build.BuildId)'
    SourcePath: '$(Build.BinariesDirectory)'
    OutputPath: '$(Build.BinariesDirectory)\drop'
    Overwrite: true

- task: ArchiveFiles@1
  displayName: 'Archive files '
  inputs:
    includeRootFolder: false
    archiveFile: '$(Build.BinariesDirectory)/FabrikamFiber.1.0.$(Build.BuildId).zip'
  enabled: false

- task: CopyPublishBuildArtifacts@1
  displayName: 'Copy Publish Artifact: FabrikamFiberWeb'
  inputs:
    CopyRoot: '$(Build.BinariesDirectory)'
    Contents: '**\*.zip'
    ArtifactName: FabrikamFiberWeb
    ArtifactType: Container

- task: CopyPublishBuildArtifacts@1
  displayName: 'Copy Publish Artifact: FabrikamFiberDB'
  inputs:
    CopyRoot: '$(build.sourcesDirectory)'
    Contents: '**\FabrikamDB\bin\Release\**'
    ArtifactName: FabrikamFiberDB
    ArtifactType: Container

- task: OctopusPush@2
  displayName: 'Push Packages to Octopus'
  inputs:
    OctoConnectedServiceName: OctopusCloud
    Package: '$(Build.BinariesDirectory)\drop\FabrikamFiber.1.0.$(Build.BuildId).zip'
    Replace: false

- task: OctopusCreateRelease@2
  displayName: 'Create Octopus Release: Projects-1'
  inputs:
    OctoConnectedServiceName: Octopus
    ProjectName: 'Projects-1'
  enabled: false

- task: OctopusDeployRelease@2
  displayName: 'Deploy Octopus Release: Fabrikam-CustomerService to fabfiber-qa'
  inputs:
    OctoConnectedServiceName: Octopus
    Project: 'Fabrikam-CustomerService'
    Environments: 'fabfiber-qa'
    ShowProgress: false
  enabled: false

